FROM node:10

RUN apt-get update && apt-get install -y \
  python

#RUN git clone https://gitlab.com/javallone/regexper-static
RUN git clone https://github.com/AkatQuas/regexper-ng
RUN cd /regexper-ng && npm install
RUN cd /regexper-ng && sed -i 's/"start": "webpack-dev-server/"start": "webpack-dev-server --host=0.0.0.0 --public regexper/g' package.json && more package.json
#COPY package.json /regexper-ng/
RUN cd /regexper-ng && npm install gulp 
RUN cd /regexper-ng && yarn build

EXPOSE 8080

CMD cd /regexper-ng && yarn start

